package com.nextep.pelmel.model;

/**
 * Created by cfondacci on 29/07/15.
 */
public enum Action {
    LIKE, UNLIKE,ATTEND,UNATTEND,CHECKIN, CHECKOUT, CHAT, LIST_DEALS,
    NETWORK_REQUEST, NETWORK_ACCEPT, NETWORK_CANCEL, NETWORK_INVITE, NETWORK_RESPOND, NETWORK_LIST
}
